{"uuid": "349a9821-d0db-4262-a833-f7c1e4fe74e9", "children": ["5cc03f1b-90b4-419c-acc7-880ec603c43a"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'driver' referenced before assignment\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/zhangxiangkui/Downloads/AutomationTest/testcase/conftest.py\", line 35, in start_appium_desired\n    return driver\n"}, "start": 1587405218998, "stop": 1587405219012}], "start": 1587405218998, "stop": 1587405219072}